about/urls.py
from django.urls import path
from .views import AboutListView

about_patterns = ([
    path('', AboutListView.as_view(), name="about"),
], 'about')

amdweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core.urls import core_patterns
from about.urls import about_patterns
from portfolio.urls import portfolio_patterns
from contact.urls import contact_patterns
from blog.urls import blog_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_patterns)),
    path('about/', include(about_patterns)),
    path('portfolio/', include(portfolio_patterns)),
    path('contact/', include(contact_patterns)),
    path('blog/', include(blog_patterns)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, CategoryListView

blog_patterns = ([
    path('', BlogListView.as_view(), name="post_list"),
    path('<int:pk>/', BlogDetailView.as_view(), name="post_detail"),
    path('category/<int:pk>/', CategoryListView.as_view(), name="post_list_category"),
], 'blog')

about/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    institution = models.CharField(max_length=200, verbose_name="Institución")
    description = models.CharField(max_length=800 ,verbose_name="Descripción del curso")
    extra = models.CharField(max_length=800 ,verbose_name="Información extra", null=True, blank=True)
    start_date = models.DateTimeField(verbose_name="Fecha de inicio del curso")
    finish_date = models.DateTimeField(verbose_name="Fecha de finalización del curso", null=True, blank=True)
    image = models.ImageField(verbose_name="Imagen", upload_to="about", null=True, blank=True)
    order = models.SmallIntegerField(verbose_name="Ordenación", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['order','-updated']

    def __str__(self):
        return self.institution + " - " + self.description

# Create your models here.
class Job(models.Model):
    institution = models.CharField(max_length=200, verbose_name="Institución")
    description = models.CharField(max_length=800 ,verbose_name="Descripción del trabajo")
    extra = models.CharField(max_length=800 ,verbose_name="Información extra", null=True, blank=True)
    start_date = models.DateTimeField(verbose_name="Fecha de inicio del trabajo")
    finish_date = models.DateTimeField(verbose_name="Fecha de finalización del trabajo", null=True, blank=True)
    image = models.ImageField(verbose_name="Imagen", upload_to="about", null=True, blank=True)
    order = models.SmallIntegerField(verbose_name="Ordenación", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")

    class Meta:
        verbose_name = 'Trabajo'
        verbose_name_plural = 'Trabajos'
        ordering = ['order','-updated']

    def __str__(self):
        return self.institution + " - " + self.description
        

about/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from .models import Course, Job


# Create your views here.
class AboutListView(ListView):
    model = Course
    template_name = 'about/about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutListView, self).get_context_data(**kwargs)
        context.update({
            'job_list': Job.objects.all(),
        })
        return context

about/templates/about/about.html
{% extends 'core/base.html' %}

{% block title %}Sobre mí{% endblock title %}

{% load static %}
{% block background %}{% static 'core/img/about-bg.jpg' %}{% endblock background %}

{% block headers %}
    <span class="subheading">Página Web Personal</span>
    <br/>
    <h1>ÁNGEL MURCIA DÍAZ</h1>
    <h4>INGENIERO INFORMÁTICO</h4>
{% endblock headers %}

{% block content %}
    <div class="row">  
        <div class="col-lg-3 col-md-4 offset-lg-1">
            <img id="me" class="img-fluid avatar" src="{% static 'core/img/avatar.jpg' %}" alt="">
        </div>
        <div class="col-lg-7 col-md-8">
            <h2 class="section-heading">Sobre mí</h2>  
            <p>Soy Ángel Murcia Díaz, actualmente vivo en un pueblo de Córdoba, me puedo describir como alguien dinámico, proactivo, dispuesto siempre a aprender y con aficiones variadas, aunque si tuviera que destacar algunas serían: los videojuegos, los deportes y las curiosidades de las nuevas tecnologías.</p>
            <p>Desde pequeño soy un apasionado de la informática, en parte gracias a mi padre, por lo que empecé mis estudios en la informática mucho antes de comenzar con el grado, por ejemplo, aprendí conocimientos básicos de programación, diseñé y realicé páginas web e incluso pequeños "programas" de forma sencilla.</p>
            <p>Con la edad he ido adquiriendo aún más interés por todo lo relacionado con este "mundo" y estos últimos años la universidad me ha servido para ampliar notablemente mis conocimientos. Ahora estoy interesado en entrar al mundo laboral para poder seguir formándome y aprendiendo.</p>
            <p>Pienso que la clave del éxito reside en que te guste tu trabajo, por eso sé con seguridad que no estuve equivocado al escoger estudiar ingeniería informática para ejercer algún día esta profesión.</p>
            <p>Ahora estoy interesado en entrar al mundo laboral para poder seguir aprendiendo y formándome.</p>
            <p>Soy una persona curiosa, lo que me ha llevado a ir siempre un paso más allá, si explicaban algo en clase me encargaba de profundizar más en el tema, esto me ha empujado a investigar por mí mismo.</p>
            <p>Finalmente, destaco que me encanta pasar tiempo con mis amigos y como conocer a nuevas personas, por lo que considero el trabajo en equipo fundamental en cualquier ámbito de la vida.</p>
        </div>
    </div>
    <div class="row">  
        <div class="col-lg-3 col-md-4 offset-lg-1"></div>
        <div class="col-lg-7 col-md-8">
            <h2 class="section-heading">Educación</h2> 
        </div>
    </div>
    {% for course in course_list %}
        <div class="row project">  
        {% if course.image.url != "" %}	
            <div class="col-lg-3 col-md-4 offset-lg-1">
                    <img class="img-fluid" src="{{course.image.url}}"alt="">
            </div>
        {% endif %}
        <div class="col-lg-7 col-md-8">
            <h5>{{course.institution}}</h5>     
            <p>{{course.description}}</p>
            {% if course.extra != None %}
                <p class="extra">{{course.extra}}</p>
            {% endif %}
            <p>{{course.start_date|date:'Y'}} - {{course.finish_date|date:'Y'}}</p>
        </div>
        </div>
    {% endfor %}

    <div class="row">  
        <div class="col-lg-3 col-md-4 offset-lg-1"></div>
        <div class="col-lg-7 col-md-8">
            <h2 class="section-heading">Experiencia</h2> 
        </div>
    </div>
    {% for job in job_list %}
        <div class="row project">  
        {% if job.image.url != "" %}	
            <div class="col-lg-3 col-md-4 offset-lg-1">
                    <img class="img-fluid" src="{{job.image.url}}"alt="">
            </div>
        {% endif %}
        <div class="col-lg-7 col-md-8">
            <h5>{{job.institution}}</h5>   
            <p>{{job.description}}</p>
            {% if job.extra != None %}
                <p class="extra">{{job.extra}}</p>
            {% endif %}
            {% if job.finish_date != None %}
                <p>{{job.start_date|date:'m/Y'}} - {{job.finish_date|date:'m/Y'}}</p>
            {% else %}
                <p>{{job.start_date|date:'m/Y'}} - actualidad</p>
            {% endif %}
        </div>
        </div>
    {% endfor %}
            
{% endblock content %}